services:
  coordinator:
    image: basho/riak-kv
    ports:
      - "8087"
      - "8098"
    environment:
      - CLUSTER_NAME=riakkv
    labels:
      - "com.basho.riak.cluster.name=riak-kv"
    volumes:
      - schemas:/etc/riak/schemas
      - coordinator_data:/var/lib/riak
      - coordinator_logs:/var/log/riak
    network_mode: bridge
  member:
    image: basho/riak-kv
    ports:
      - "8087"
      - "8098"
    labels:
      - "com.basho.riak.cluster.name=riak-kv"
    links:
      - coordinator
    network_mode: bridge
    depends_on:
      - coordinator
    environment:
      - CLUSTER_NAME=riakkv
      - COORDINATOR_NODE=coordinator

volumes:
  schemas: {}
  coordinator_data: {}
  coordinator_logs: {}
