services:
  neo4j1:
    image: neo4j:5.20.0-enterprise
    container_name: neo4j1
    hostname: neo4j1
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    networks:
      - neo4j-cluster
    environment:
      NEO4J_initial_server_mode__constraint: PRIMARY
      NEO4J_dbms_cluster_discovery_endpoints: neo4j1:5000,neo4j2:5000,neo4j3:5000
      NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
      NEO4J_server_bolt_advertised__address: neo4j1:7687
      NEO4J_server_http_advertised__address: neo4j1:7474
      NEO4J_AUTH: neo4j/neo4j123
      NEO4J_initial_dbms_default__primaries__count: 3
      NEO4J_initial_dbms_default__database: diagramas
    volumes:
      - neo4j1-data:/data
      - neo4j1-logs:/logs

  neo4j2:
    image: neo4j:5.20.0-enterprise
    container_name: neo4j2
    hostname: neo4j2
    ports:
      - "8474:7474"
      - "8473:7473"
      - "8687:7687"
    networks:
      - neo4j-cluster
    environment:
      NEO4J_initial_server_mode__constraint: PRIMARY
      NEO4J_dbms_cluster_discovery_endpoints: neo4j1:5000,neo4j2:5000,neo4j3:5000
      NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
      NEO4J_server_bolt_advertised__address: neo4j2:7687
      NEO4J_server_http_advertised__address: neo4j2:7474
      NEO4J_AUTH: neo4j/neo4j123
      NEO4J_initial_dbms_default__primaries__count: 3
      NEO4J_initial_dbms_default__database: diagramas
    volumes:
      - neo4j2-data:/data
      - neo4j2-logs:/logs

  neo4j3:
    image: neo4j:5.20.0-enterprise
    container_name: neo4j3
    hostname: neo4j3
    ports:
      - "9474:7474"
      - "9473:7473"
      - "9687:7687"
    networks:
      - neo4j-cluster
    environment:
      NEO4J_initial_server_mode__constraint: PRIMARY
      NEO4J_dbms_cluster_discovery_endpoints: neo4j1:5000,neo4j2:5000,neo4j3:5000
      NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
      NEO4J_server_bolt_advertised__address: neo4j3:7687
      NEO4J_server_http_advertised__address: neo4j3:7474
      NEO4J_AUTH: neo4j/neo4j123
      NEO4J_initial_dbms_default__primaries__count: 3
      NEO4J_initial_dbms_default__database: diagramas
    volumes:
      - neo4j3-data:/data
      - neo4j3-logs:/logs
networks:
  neo4j-cluster:
    driver: bridge

volumes:
  neo4j1-data:
  neo4j1-logs:
  neo4j2-data:
  neo4j2-logs:
  neo4j3-data:
  neo4j3-logs:
