-- @autor: Luis Axel Núñez Quintana
-- @Fecha creación: 01-06-2024
-- @Descripción: Script de operaciones ddl inicial para diagram_db

-- 
-- TABLE: CONTRASENA 
--
CREATE TABLE CONTRASENA(
    CONTRASENA_ID  	numeric(10, 0)  NOT NULL,
    CONTRASENA_HASH	varchar(100)    NOT NULL,
    USUARIO_ID     	numeric(10, 0)  NOT NULL,
    CONSTRAINT CONTRASENA_PK PRIMARY KEY (CONTRASENA_ID)
);

-- 
-- TABLE: PERMISO 
--
CREATE TABLE PERMISO(
    PERMISO_ID   numeric(2, 0)    NOT NULL,
    DESCRIPCION  varchar(200)     NOT NULL,
    CONSTRAINT PERMISO_PK PRIMARY KEY (PERMISO_ID)
);

-- 
-- TABLE: ROL 
--
CREATE TABLE ROL(
    ROL_ID  numeric(2, 0)    NOT NULL,
    NOMBRE  varchar(20)      NOT NULL,
    CONSTRAINT ROL_PK PRIMARY KEY (ROL_ID)
);

-- 
-- TABLE: ROL_PERMISO 
--
CREATE TABLE ROL_PERMISO(
    ROL_ID      numeric(2, 0)    NOT NULL,
    PERMISO_ID  numeric(2, 0)    NOT NULL,
    CONSTRAINT ROL_PERMISO_PK PRIMARY KEY (ROL_ID, PERMISO_ID)
);

-- 
-- TABLE: USUARIO 
--
CREATE TABLE USUARIO(
    USUARIO_ID      numeric(10, 0)    NOT NULL,
    NOMBRE_USUARIO  varchar(40)       NOT NULL,
    EMAIL           varchar(40)       NOT NULL,
    FECHA_CREACION  timestamp         NOT NULL,
    ULTIMA_SESION   timestamp         NOT NULL,
    ROL_ID	    numeric(2, 0)     NOT NULL,
    CONSTRAINT USUARIO_PK PRIMARY KEY (USUARIO_ID)
);

--
-- FK INDEXES
--
CREATE INDEX CONTRASENA_USUARIO_ID_IX ON CONTRASENA(USUARIO_ID);

CREATE INDEX ROL_PERMISO_ROL_ID_IX ON ROL_PERMISO(ROL_ID);

CREATE INDEX ROL_PERMISO_PERMISO_ID_IX ON ROL_PERMISO(PERMISO_ID);

CREATE INDEX USUARIO_ROL_ID_IX ON USUARIO(ROL_ID);

--
-- FK CONSTRAINTS
--

-- 
-- TABLE: CONTRASENA 
--
ALTER TABLE CONTRASENA ADD CONSTRAINT CONTRASENA_USUARIO_USUARIO_ID_FK
    FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIO(USUARIO_ID);

-- 
-- TABLE: ROL_PERMISO 
--
ALTER TABLE ROL_PERMISO ADD CONSTRAINT ROL_PERMISO_ROL_ROL_ID_FK
    FOREIGN KEY (ROL_ID)
    REFERENCES ROL(ROL_ID);

ALTER TABLE ROL_PERMISO ADD CONSTRAINT ROL_PERMISO_PERMISO_PERMISO_ID_FK
    FOREIGN KEY (PERMISO_ID)
    REFERENCES PERMISO(PERMISO_ID);

-- 
-- TABLE: USUARIO
--
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_ROL_ROL_ID_FK
    FOREIGN KEY (ROL_ID)
    REFERENCES ROL(ROL_ID);
